config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "blog"           => "blog#index",       as: :posts
  get "blog/:slug"     => "blog#show",        as: :post
  get "projects"       => "projects#index",   as: :projects
  get "projects/:slug" => "projects#show",    as: :project
  get "resume"         => "welcome#resume",   as: :resume

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base # rubocop:disable Style/Documentation
  primary_abstract_class

  class << self
    # If you want to exclude a model from the sitemap, you can override this method to return true
    def noindex = false
  end
end

app/models/post.rb
# frozen_string_literal: true

# This is the Post model that represents the blog posts that James Ebentier writes.
class Post < ApplicationRecord
  declare_schema id: :uuid, default: 'gen_random_uuid()' do
    string :slug,        limit: 255,  null: false, validates: { presence: true, uniqueness: { case_sensitive: false } }, index: { unique: true }
    string :title,       limit: 1024, null: false, validates: { presence: true }
    string :description, limit: 1024, null: false, validates: { presence: true }
    string :keywords,    limit: 1024, null: false, validates: { presence: true }
    string :image,       limit: 1024, null: false, default: ""
    string :file_path,   limit: 1024, null: false, validates: { presence: true }

    json   :tags, null: false, default: []

    datetime :published_at, null: false, validates: { presence: true }
  end

  before_validation -> { self.slug = slug.downcase if slug.present? }

  scope :published, -> { where(published_at: ..Time.zone.now) }

  def content
    @content ||= begin
      file_content = Rails.public_path.join('blog', file_path).read
      file_content.split("---\n", 3).last.chomp
    end
  end
end

app/models/project.rb
# frozen_string_literal: true

# This is the Project model that represents the projects that James Ebentier is working on.
class Project < ApplicationRecord
  declare_schema id: :uuid, default: 'gen_random_uuid()' do
    string :slug,   limit: 255,  null: false, validates: { presence: true, uniqueness: true }, index: { unique: true }
    string :title,  limit: 1024, null: false, validates: { presence: true }
    string :status, limit: 255, null: false,  validates: { presence: true, inclusion: { in: %w[Pre-Launch Beta Live] } },
                    default: 'Beta'
    string :url,    limit: 1024, null: false, validates: { presence: true }
    string :image,  limit: 1024, null: false, validates: { presence: true }
    text   :description, null: false, validates: { presence: true }
  end

  def content
    @content ||= if (file_path = Rails.public_path.join('projects', "#{slug}.md")).exist?
                   file_path.read
                 else
                   '_Project Details Coming Soon_'
                 end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base # rubocop:disable Style/Documentation
  class << self
    # If you want to exclude a controller from the sitemap, you can override this method to return true
    def noindex = false
  end

  def default_url_options
    if Rails.env.production?
      { host: "jamesebentier.com" }
    else
      {}
    end
  end
end

app/controllers/blog_controller.rb
# frozen_string_literal: true

# The BlogController is used to host the blog posts for the application.
class BlogController < ApplicationController
  def index; end

  def show
    @post = Post.find_by!(slug: params[:slug].downcase)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController # rubocop:disable Style/Documentation
  def index; end

  def show
    @project = Project.find_by(slug: params[:slug])
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

# The WelcomeController is used to host the landing pages and supplimentary content for the application.
class WelcomeController < ApplicationController
  def index; end
  def projects; end
  def resume; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper # rubocop:disable Style/Documentation
  def social_profile_icon(network, classes: nil, **)
    case network.to_sym
    when :linkedin
      tag.i class: "fa-brands fa-linkedin text-base text-[#0072b1] #{classes}", title: "LinkedIn", **
    when :twitter
      tag.i class: "fa-brands fa-twitter text-base text-[#1da1f2] #{classes}", title: "Twitter", **
    else
      tag.i class: "fa-brands fa-#{network} text-base #{classes}", title: network.capitalize, **
    end
  end
end

app/helpers/blog_helper.rb
# frozen_string_literal: true

require 'blog/renderer'

module BlogHelper # rubocop:disable Style/Documentation
  def render_markdown(content)
    markdown = Redcarpet::Markdown.new(Blog::Renderer, autolink: true, tables: true)
    markdown.render(content).html_safe # rubocop:disable Rails/OutputSafety
  end
end

app/helpers/resume_helper.rb
# frozen_string_literal: true

module ResumeHelper # rubocop:disable Style/Documentation
  def resume_data
    @resume_data ||= YAML.safe_load_file(Rails.root.join("resume/resume.yml"), symbolize_names: true)
  end

  def style_for_level(level) # rubocop:disable Metrics/MethodLength
    case level.downcase
    when 'master', 'native-speaker'
      'after:bg-[#59C596] after:w-full'
    when 'advanced'
      'after:bg-[#5CB85C] after:w-3/4'
    when 'intermediate'
      'after:bg-[#ffdf1f] after:w-1/2'
    when 'beginner'
      'after:bg-black after:w-1/4'
    else
      'after:bg-[#9e9e9e]'
    end
  end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/blog/index.html.erb
<% content_for :head do %>
  <%= auto_discovery_link_tag(:rss, posts_url(format: "rss")) %>
<% end %>

<%
  set_meta_tags(
    title: 'Blog',
    description: "Stay up-to-date with James Ebentier's latest discoveries, learning, and thoughts through my blog posts.",
  )
%>

<h1 class='text-3xl mb-4'>Recent Blog Posts</h1>
<% Post.published.order(published_at: :desc).each do |post| %>
  <%= link_to post_path(slug: post.slug), class: 'flex flex-row mb-6 p-6 border border-[#eaeaea] rounded bg-white shadow text-justify w-full text-black no-underline' do %>
    <div class='p-4 mr-4 w-40 align-middle m-auto flex-shrink-0'>
      <img src="<%= post.image %>" alt="<%= post.title %>" class='m-auto' />
    </div>
    <div class='m-auto flex-grow'>
      <h2 class='text-2xl text-left'><%= post.title %></h2>
      <p class='text-sm text-[#999] my-2'>Published At: <%= post.published_at.strftime("%B %d, %Y") %></p>
      <p class='mb-0'><%= post.description %></p>
    </div>
  <% end %>
<% end %>

app/views/blog/show.html.erb
<%
  set_meta_tags(
    title: @post.title,
    description: @post.description,
    canonical: post_url(@post.slug),
    og: { url: post_url(@post.slug), image: "https://jamesebentier.com/#{@post.image}" },
    twitter: { image: "https://jamesebentier.com/#{@post.image}" }
  )
%>
<main class="mx-auto p-4">
  <article class="flex justify-center">
    <div class="bg-white rounded shadow-lg px-12 py-6 prose lg:prose-base lg:w-full lg:max-w-screen-lg">
      <%- if @post.image %>
      <figure class="flex justify-center">
        <img src="<%= @post.image %>" alt="<%= @post.title %>" class="rounded bg-base-200 max-h-72">
      </figure>
      <% end %>
      <h1 class="text-3xl font-bold mb-4"><%= @post.title %></h1>
      <div class="flex gap-3 mb-4">
        <% @post.tags.each do |tag| %>
          <span class="badge badge-accent">#<%= tag %></span>
        <% end %>
      </div>
      <div class="flex gap-3">
				<span class="badge badge-ghost">
					<time datetime="<%= @post.published_at.iso8601 %>"><%= @post.published_at.strftime("%B %d, %Y") %></time>
				</span>
				<span class="text-sm text-base-content/70">By James Ebentier</span>
			</div>
      <div>
        <%= render_markdown(@post.content) %>
      </div>
    </div>
  </article>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme='light'>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%=
      display_meta_tags(
        site: t('site.name'),
        separator: '|',
        reverse: true,
        follow: true,
        index: true,
        og: {
          title: :title,
          description: :description,
          type: 'website',
          site_name: :site,
          url: request.original_url,
          image: 'https://jamesebentier.com/logo192.png'
        },
        twitter: {
          card: 'summary_large_image',
          title: :title,
          description: :description,
          site: t('site.twitter_handle'),
          creator: t('site.owner_twitter_handle'),
          image: 'https://jamesebentier.com/logo192.png'
        }
      )
    %>

    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico">
    <link rel="apple-touch-icon" href="/logo192.png" />
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
    <link rel="manifest" href="/manifest.json" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <script src="https://kit.fontawesome.com/d7b2096eb7.js" crossorigin="anonymous"></script>
    <%- if Rails.env.production? %>
    <script>function loadScript(a){var b=document.getElementsByTagName("head")[0],c=document.createElement("script");c.type="text/javascript",c.src="https://tracker.metricool.com/resources/be.js",c.onreadystatechange=a,c.onload=a,b.appendChild(c)}loadScript(function(){beTracker.t({hash:"88e45cec281a34f78c4a2745481794d3"})});</script>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-TWP4CV64DK"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-TWP4CV64DK');
    </script>
    <% end %>
  </head>

  <body>
    <%= render partial: 'layouts/components/header' %>
    <div class="max-w-screen-lg m-auto font-sans-serif">
      <%= yield %>
    </div>
    <%= render partial: 'layouts/components/footer' %>
  </body>
</html>

app/views/layouts/components/_footer.html.erb
<footer class="bg-base-200 border-t border-base-content/10">
    <div class="max-w-7xl mx-auto px-8 py-24">
      <div class=" flex lg:items-start md:flex-row md:flex-nowrap flex-wrap flex-col">
        <div class="w-64 flex-shrink-0 md:mx-0 mx-auto text-center md:text-left">
          <a href="/#" aria-current="page" class="flex gap-2 justify-center md:justify-start items-center">
            <img src='/favicon.ico' alt="James Ebentier" class='w-6 h-6' width='24' height='24' />
            <strong class="font-extrabold tracking-tight text-base md:text-lg">
              James Ebentier
            </strong>
          </a>

          <p class="mt-3 text-sm text-base-content/60">
            Copyright © James Ebentier <%= Date.today.year %> - All rights reserved
          </p>
        </div>
        <div class="flex-grow flex flex-wrap justify-center -mb-10 md:mt-0 mt-10 text-center">
          <div class="lg:w-1/4 md:w-1/2 w-full px-4">
            <div class="footer-title font-semibold text-base-content tracking-widest text-sm md:text-left mb-3">
              Links
            </div>

            <ul class='flex flex-col list-none justify-center items-center md:items-start gap-2 mb-10 text-sm'>
              <%= link_to 'Blog', posts_url, class: 'link link-hover' %>
              <%= link_to 'Projects', projects_url, class: 'link link-hover' %>
              <%= link_to 'Resume', resume_url, class: 'link link-hover' %>
            </ul>
          </div>

          <div class="lg:w-1/4 md:w-1/2 w-full px-4">
            <div class="footer-title font-semibold text-base-content tracking-widest text-sm md:text-left mb-3">
              Social
            </div>

            <div class="flex flex-row space-x-4 items-start mb-10 text-sm">
              <a href='https://twitter.com/jebentier' rel='noreferrer' target='_blank' title='jebentier twitter account' data-controller='mui-icons'><%= social_profile_icon :twitter %></a>
              <a href='https://linkedin.com/in/jebentier' rel='noreferrer' target='_blank' title='jebentier linkedin account'><%= social_profile_icon :linkedin %></a>
              <a href='https://github.com/jebentier' rel='noreferrer' target='_blank' title='jebentier github account'><%= social_profile_icon :github %></a>
            </div>
          </div>
          <div class="lg:w-1/4 md:w-1/2 w-full px-4">
            <div class="footer-title font-semibold text-base-content tracking-widest text-sm md:text-left mb-3">
              Feeds
            </div>

            <div class="flex flex-col justify-center items-center md:items-start gap-2 mb-10 text-sm">
              <%= link_to posts_url(format: "rss"), target: "_blank", title: "blog rss feed" do %>
                <i class="fa-solid fa-square-rss text-orange-400 text-base"></i> Blog
              <% end %>
              <%= link_to projects_url(format: "rss"), target: "_blank", title: "projects rss feed", class: 'link link-hover' do %>
                <i class="fa-solid fa-square-rss text-orange-400 text-base"></i> Projects
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/components/_header.html.erb
<header class='w-full shadow mb-8 print:hidden'>
  <div class='flex w-full max-w-7xl mx-auto px-8 py-4 print:hidden'>
    <img src="/favicon.ico" alt="James Ebentier" class='h-9 justify-self-start' />
    <ul class='flex flex-row list-none ml-auto content-center items-center justify-end my-auto'>
      <li class='ml-4'><%= link_to 'Home', root_url, class: current_page?(root_path) ? 'text-[#fab73a] cursor-default' : 'link link-hover' %></li>
      <li class='ml-4'><%= link_to 'Blog', posts_url, class: current_page?(posts_path) ? 'text-[#fab73a] cursor-default' : 'link link-hover' %></li>
      <li class='ml-4'><%= link_to 'Projects', projects_url, class: current_page?(projects_url) ? 'text-[#fab73a] cursor-default' : 'link link-hover' %></li>
      <li class='ml-4'><%= link_to 'Resume', resume_path, class: current_page?(resume_url) ? 'text-[#fab73a] cursor-default' : 'link link-hover' %></li>
    </ul>
  </div>
</header>

app/views/projects/index.html.erb
<% content_for :head do %>
  <%= auto_discovery_link_tag(:rss, projects_url(format: "rss")) %>
<% end %>

<%
  set_meta_tags(
    title: 'Projects',
    description: "Stay up-to-date with James Ebentier's latest projects released to the public through BiTi LLC",
  )
%>

<h1 class='text-3xl mb-4'>Recent Projects</h1>
<% Project.find_each do |project| %>
  <%= link_to project_url(slug: project.slug), class: 'flex flex-row mb-6 p-6 border border-[#eaeaea] rounded bg-white shadow text-justify w-full text-black no-underline' do %>
    <div class='p-4 w-1/3 align-middle m-auto'>
      <img src="<%= project.image %>" alt="<%= project.title %>" class='m-auto' />
    </div>
    <div class='m-auto'>
      <h2 class='text-2xl text-left'><%= project.title %></h2>
      <p class='text-sm text-[#999] my-2'>Status: <%= project.status %></p>
      <p class='text-sm text-[#999] my-2'>URL: <%= project.url %></p>
      <p class='mb-0'><%= project.description %></p>
    </div>
  <% end %>
<% end %>

app/views/projects/show.html.erb
<%
  set_meta_tags(
    title: @project.title,
    description: @project.description,
  )
%>

<div class='flex flex-row mb-6 space-x-4'>
  <div class='p-4 w-1/4 align-top m-auto mt-0 flex-shrink-0 border rounded shadow'>
    <img src="<%= @project.image %>" alt="<%= @project.title %>" class='m-auto' />
    <p class='text-sm text-[#999] my-2 w-full text-center'>
      <%= link_to @project.url, @project.url, target: '_blank', rel: 'noreferrer', class: 'link link-hover underline' %>
    </p>
    <p class='text-sm text-[#999] my-2 w-full text-center'>
      <span class='badge badge-accent'><%= @project.status %></span>
    </p>
  </div>
  <div class='p-4 m-auto border rounded shadow'>
    <h1 class='text-3xl mb-5'><%= @project.title %></h1>
    <div class='prose w-full max-w-none'>
      <%= render_markdown(@project.content) %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class='text-lg font-extralight text-center'>
  <p class='my-8 mx-auto max-w-2xl'>
    Hello, my name is <strong class='text-2xl m-3 text-green-500'>James Ebentier.</strong>
    <br />
    I am a <strong class='text-2xl m-3 text-purple-500'>Software Architect</strong> for <a href='https://invoca.com' target='_blank' rel='noreferrer' class='font-medium'>Invoca Inc.</a>
    <br/>
    based out of <strong class='text-2xl m-3 text-orange-500'>Berlin, Germany.</strong>
    <br/>
    Outside of work I am a <strong class='text-2xl m-3 text-pink-500'>hacker</strong>, community <strong class='text-2xl m-3 text-yellow-600'>advocate</strong>, and <strong class='text-2xl m-3 text-fuchsia-500'>mentor</strong> to any and all who seek it.
  </p>
  <%= image_tag 'landing-image.webp', alt: 'James Ebentier Banner', class: 'w-full rounded-xl mb-8' %>
</div>

app/views/welcome/projects.html.erb
<% content_for :head do %>
  <%= auto_discovery_link_tag(:rss, projects_url(format: "rss")) %>
<% end %>

<h1 class='text-3xl mb-4'>Recent Projects</h1>
<% Project.find_each do |project| %>
  <%= link_to project.url, target: '_blank', rel: 'noreferrer', class: 'flex flex-row mb-6 p-6 border border-[#eaeaea] rounded bg-white shadow text-justify w-full text-black no-underline' do %>
    <div class='p-4 w-1/3 align-middle m-auto'>
      <img src="<%= project.image %>" alt="<%= project.title %>" class='m-auto' />
    </div>
    <div class='m-auto'>
      <h2 class='text-2xl text-left'><%= project.title %></h2>
      <p class='text-sm text-[#999] my-2'>Status: <%= project.status %></p>
      <p class='mb-0'><%= project.description %></p>
    </div>
  <% end %>
<% end %>

app/views/welcome/resume.html.erb
<%
  set_meta_tags(
    title: 'Resume',
    description: "The fully interactive resume of James Ebentier, a full-stack developer with a passion for learning and creating.",
  )
%>
<div class='text-sm mx-auto my-10 text-[#40484f] font-resume text-justify leading-snug'>
  <%= render partial: 'welcome/resume/header',          locals: resume_data %>
  <%= render partial: 'welcome/resume/main_summary',    locals: resume_data %>
  <%= render partial: 'welcome/resume/skills',          locals: resume_data %>
  <%= render partial: 'welcome/resume/work_experience', locals: resume_data %>
  <%= render partial: 'welcome/resume/education',       locals: resume_data %>
  <%= render partial: 'welcome/resume/languages',       locals: resume_data %>
</div>

app/views/welcome/resume/_education.html.erb
<div class='my-4'>
  <div class="relative mb-2 after:absolute after:left-0 after:top-3 after:h-px after:w-full after:bg-[#ccc] after:block after:content-[''] after:-z-10">
    <h2 class='pr-4 bg-white text-[#ff6d1f] inline-block uppercase font-semibold text-base mb-0'>Education (<%= education.count %>)</h2>
  </div>
  <div>
    <% education.each do |data| %>
      <div class='mb-6 w-full flex flex-row' key={key}>
        <div class='ml-10'>
          <div class='inline-block font-semibold'><%= data[:studyType] %> <%= data[:area] %></div>
          <div class='inline-block text-[#606d76] font-normal before:mx-2 before:content-["|"]'><%= data[:institution] %></div>
        </div>
        <div class='ml-auto font-semibold'>
          <div class='inline-block'><%= Date.parse(data[:startDate]).strftime('%B %Y') %></div>
          <div class='inline-block before:mx-2 before:content-["-"]'><%= data[:endDate] ? Date.parse(data[:endDate]).strftime('%B %Y') : 'Current' %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/resume/_header.html.erb
<div class="header flex flex-grow">
  <div>
    <h1 class='text-4xl font-thin leading-normal'><%= basics[:name] %></h1>
    <h2 class='text-2xl font-light text-[#202931]'><%= basics[:label] %></h2>
    <div class='mb-1'><%= basics.dig(:location, :postalCode) %>, <%= basics.dig(:location, :city) %>, <%= basics.dig(:location, :region) %> <%= basics.dig(:location, :countryCode) %></div>
    <div class='flex flex-row justify-left mb-1'>
      <div class='mr-2'>
        <i class="fa-solid fa-up-right-from-square mx-1 my-auto align-middle text-sm"></i>
        <a href="<%= basics[:website] %>" class='link link-hover my-auto align-middle'><%= basics[:website] %></a>
      </div>
      <div class='mx-2'>
        <i class="fa-solid fa-envelope mx-1 my-auto align-middle text-sm"></i>
        <a href="mailto:<%= basics[:email] %>" class='link link-hover my-auto align-middle'><%= basics[:email] %></a>
      </div>
      <div class='mx-y'>
        <i class="fa-solid fa-phone mx-1 my-auto align-middle text-sm"></i>
        <a href="tel:<%= basics[:phone] %>" class='link link-hover my-auto align-middle'><%= basics[:phone] %></a>
      </div>
    </div>
    <div class='flex flex-row justify-left mb-1'>
      <% basics[:profiles].each do |profile| %>
        <div class='mr-3'>
          <%= social_profile_icon profile[:network], classes: 'my-auto align-middle' %>
          <a href="<%= profile[:url] %>" class='link link-hover my-auto align-middle'><%= profile[:username] %></a>
        </div>
      <% end %>
    </div>
  </div>
  <img class='w-44 h-full m-auto mr-0 rounded justify-self-right' src="<%= basics[:picture] %>" alt="<%= basics[:name] %>" />
</div>

app/views/welcome/resume/_languages.html.erb
<div class='my-4'>
  <div class="relative mb-2 after:absolute after:left-0 after:top-3 after:h-px after:w-full after:bg-[#ccc] after:block after:content-[''] after:-z-10">
    <h2 class='pr-4 bg-white text-[#ff6d1f] inline-block uppercase font-semibold text-base mb-0'>Languages</h2>
  </div>
  <div class='flex flex-row justify-between'>
    <% languages.each do |data| %>
      <div class='w-1/3 px-4'>
        <h3 class='text-base font-semibold'><%= data[:language] %></h3>
        <div class='mb-2'>
          <em class='color-[#757575]'><%= data[:fluency] %></em>
          <div class="bar border border-[#dddddd] w-full h-2 relative block after:absolute after:content-[' '] after:top-0 after:left-0 after:h-2 <%= style_for_level(data[:fluency].downcase.gsub(" ", "-")) %>"></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/resume/_main_summary.html.erb
<div class='my-4 rounded py-5 px-4 bg-[#f1f8ff]'>
  <%= basics[:summary] %>
</div>

app/views/welcome/resume/_skills.html.erb
<div class='my-4'>
  <div class="relative mb-2 after:absolute after:left-0 after:top-3 after:h-px after:w-full after:bg-[#ccc] after:block after:content-[''] after:-z-10">
    <h2 class='pr-4 bg-white text-[#ff6d1f] inline-block uppercase font-semibold text-base mb-0'>Skills</h2>
  </div>
  <div class='flex flex-row justify-between'>
    <% skills.each do |data| %>
      <div class='w-1/3 px-4'>
        <h3 class='text-base font-semibold'><%= data[:name] %></h3>
        <div class='mb-2'>
          <em class='color-[#757575]'><%= data[:level] %></em>
          <div class="bar border border-[#dddddd] w-full h-2 relative block after:absolute after:content-[' '] after:top-0 after:left-0 after:h-2 <%= style_for_level(data[:level]) %>"></div>
        </div>
        <ul class='list-none p-0'>
          <% data[:keywords].each do |keyword| %>
            <li class='inline-block m-1 p-2 text-xs leading-none lowercase text-[#3e6d8e] bg-[#dfeaf1] text-nowrap'><%= keyword %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/welcome/resume/_work_experience.html.erb
<div class='my-4'>
  <div class="relative mb-2 after:absolute after:left-0 after:top-3 after:h-px after:w-full after:bg-[#ccc] after:block after:content-[''] after:-z-10">
    <h2 class='pr-4 bg-white text-[#ff6d1f] inline-block uppercase font-semibold text-base mb-0'>Work Experience (<%= work.count %>)</h2>
  </div>
  <div>
    <% work.each_with_index do |data, index| %>
      <div class='collapse mb-5 w-full' data-controller='collapse'>
        <div class='flex flex-row' data-action='click->collapse#toggle'>
          <i class="fa-solid fa-caret-right mt-1 ml-1 mr-3 cursor-pointer print:hidden" data-collapse='arrow'></i>
          <div>
            <div class='inline-block font-semibold'><%= data[:position] %></div>
            <div class='inline-block text-[#606d76] font-normal before:content-["|"] before:mx-2'><%= data[:company] %></div>
            <div><a href=<%= data[:website] %> target='_blank' rel='noreferrer'><%= data[:website] %></a></div>
          </div>
          <div class='ml-auto font-semibold'>
            <div class='inline-block'><%= Date.parse(data[:startDate]).strftime('%B %Y') %></div>
            <div class='inline-block before:mx-2 before:content-["-"]'><%= data[:endDate] ? Date.parse(data[:endDate]).strftime('%B %Y') : 'Current' %></div>
          </div>
        </div>
        <div class="<%= index.zero? ? "" : "hidden" %> ml-5 print:block" data-collapse='content'>
          <div class='rounded py-5 px-4 bg-white'><%= data[:summary] %></div>
          <%- if data[:highlights] %>
            <ul class='list-square pl-10'>
              <% data[:highlights].each do |highlight| %>
                <li><%= highlight %></li>
              <% end %>
            </ul>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>